//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendNow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_tbl_meeting
    {
        public int id { get; set; }
        public string change_type { get; set; }
        public Nullable<System.DateTime> change_date { get; set; }
        public string change_by { get; set; }
        public string meeting_code { get; set; }
        public string title { get; set; }
        public string detail { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public string organizer { get; set; }
        public string remark { get; set; }
        public string place { get; set; }
        public string link { get; set; }
        public string department { get; set; }
        public string location { get; set; }
        public Nullable<bool> type { get; set; }
        public string password { get; set; }
        public string status { get; set; }
        public string condition { get; set; }
        public Nullable<bool> certificate { get; set; }
        public string factory_id { get; set; }
        public string mode { get; set; }
        public string meeting_type { get; set; }
        public Nullable<int> limit { get; set; }
        public Nullable<bool> limit_status { get; set; }
        public string createBy { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string editBy { get; set; }
        public Nullable<System.DateTime> editDate { get; set; }
    }
}
