//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendNow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_setting_role_permission
    {
        public int id { get; set; }
        public string role { get; set; }
        public string module { get; set; }
        public Nullable<bool> viewFunction { get; set; }
        public Nullable<bool> editFunction { get; set; }
        public Nullable<bool> deleteFunction { get; set; }
        public Nullable<bool> addFunction { get; set; }
        public Nullable<bool> status { get; set; }
        public string createBy { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string editBy { get; set; }
        public Nullable<System.DateTime> editDate { get; set; }
    }
}
