//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendNow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmp_participant
    {
        public int id { get; set; }
        public string name { get; set; }
        public string location { get; set; }
        public string department { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string editBy { get; set; }
        public Nullable<System.DateTime> editDate { get; set; }
        public string remark { get; set; }
        public string factory_id { get; set; }
        public string staff_no { get; set; }
        public string password { get; set; }
        public string status { get; set; }
    }
}
